In [3]:
import pandas as pd
import matplotlib.pyplot as plt

In [11]:
df = pd.DataFrame()
df = pd.read_table("estat_tran_r_mago_nm.tsv")

In [12]:
df.head()

,"freq,tra_meas,unit,geo\TIME_PERIOD",1997,1998,1999,2000,2001,2002,2003,2004,2005,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,"A,FR_LD,THS_T,BE",60563,59340,62317,67639,66505,68422,76475,78286,89223,...,111544,112467.56,114885.62,117800.71,122302.52,125914.3,126386.94,136321.45,131389,126589.91
1,"A,FR_LD,THS_T,BE2",60563,59340,62317,67639,66505,68422,76475,78286,89223,...,111544,112467.56,114885.62,117800.71,122302.52,125914.3,126386.94,136321.45,131389,126589.91
2,"A,FR_LD,THS_T,BE21",45150,43551,43921,48072,48322,49300,58073,60097,65208,...,90749,93447.29,95407.34,98603.31,102808.48,105332.71,104288.37,109782.57,123540.78,119205.55
3,"A,FR_LD,THS_T,BE23",3729,3946,5336,4391,3987,4291,4848,3544,6028,...,6685,6571.83,7383.03,7864.59,7390.23,7671.18,7103.17,6904.52,7848.22,7384.37
4,"A,FR_LD,THS_T,BE25",11684,11844,13060,15176,14196,14831,13554,14645,17987,...,14110,12448.44,12095.25,11332.81,12103.81,12910.4,14995.41,19634.36,:,:

In [13]:
# Rename first column to something easier
df = df.rename(columns={
    df.columns[0]: "meta"
})

# Split into separate columns
df[["freq", "tra_meas", "unit", "geo"]] = df["meta"].str.split(",", expand=True)

# Drop the original combined column
df = df.drop(columns=["meta"])

In [14]:
df_long = df.melt(
    id_vars=["freq", "tra_meas", "unit", "geo"],
    var_name="year",
    value_name="value"
)

In [17]:
df_long.head(20)

   freq tra_meas   unit   geo   year   value
0     A    FR_LD  THS_T    BE  1997   60563
1     A    FR_LD  THS_T   BE2  1997   60563
2     A    FR_LD  THS_T  BE21  1997   45150
3     A    FR_LD  THS_T  BE23  1997    3729
4     A    FR_LD  THS_T  BE25  1997   11684
5     A    FR_LD  THS_T    BG  1997       :
6     A    FR_LD  THS_T   BG3  1997       :
7     A    FR_LD  THS_T  BG33  1997       :
8     A    FR_LD  THS_T  BG34  1997       :
9     A    FR_LD  THS_T    CY  1997       :
10    A    FR_LD  THS_T   CY0  1997       :
11    A    FR_LD  THS_T  CY00  1997       :
12    A    FR_LD  THS_T    DE  1997   71512
13    A    FR_LD  THS_T   DE1  1997       :
14    A    FR_LD  THS_T  DE11  1997       :
15    A    FR_LD  THS_T   DE5  1997   11389
16    A    FR_LD  THS_T  DE50  1997   11389
17    A    FR_LD  THS_T   DE6  1997   25014
18    A    FR_LD  THS_T  DE60  1997   25014
19    A    FR_LD  THS_T   DE7  1997       :