In [7]:
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
def format_df(df:pd.DataFrame, col_name_list: list):
    # Rename first column to something easier
    df = df.rename(columns={
    df.columns[0]: "meta"
    })

    # Split into separate columns
    df[col_name_list] = df["meta"].str.split(",", expand=True)

    # Drop the original combined column
    df = df.drop(columns=["meta"])

    return df

In [9]:
#Maritime transport of freight by NUTS 2 region
df = pd.DataFrame()
df = pd.read_table("estat_tran_r_mago_nm.tsv")

FileNotFoundError: [Errno 2] No such file or directory: 'estat_tran_r_mago_nm.tsv'

In [ ]:
df.head()

,"freq,tra_meas,unit,geo\TIME_PERIOD",1997,1998,1999,2000,2001,2002,2003,2004,2005,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,"A,FR_LD,THS_T,BE",60563,59340,62317,67639,66505,68422,76475,78286,89223,...,111544,112467.56,114885.62,117800.71,122302.52,125914.3,126386.94,136321.45,131389,126589.91
1,"A,FR_LD,THS_T,BE2",60563,59340,62317,67639,66505,68422,76475,78286,89223,...,111544,112467.56,114885.62,117800.71,122302.52,125914.3,126386.94,136321.45,131389,126589.91
2,"A,FR_LD,THS_T,BE21",45150,43551,43921,48072,48322,49300,58073,60097,65208,...,90749,93447.29,95407.34,98603.31,102808.48,105332.71,104288.37,109782.57,123540.78,119205.55
3,"A,FR_LD,THS_T,BE23",3729,3946,5336,4391,3987,4291,4848,3544,6028,...,6685,6571.83,7383.03,7864.59,7390.23,7671.18,7103.17,6904.52,7848.22,7384.37
4,"A,FR_LD,THS_T,BE25",11684,11844,13060,15176,14196,14831,13554,14645,17987,...,14110,12448.44,12095.25,11332.81,12103.81,12910.4,14995.41,19634.36,:,:

In [ ]:
df = format_df(df, ["freq", "tra_meas", "unit", "geo"])

df.head()

,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,...,2018,2019,2020,2021,2022,2023,freq,tra_meas,unit,geo
0,60563,59340,62317,67639,66505,68422,76475,78286,89223,92751,...,122302.52,125914.3,126386.94,136321.45,131389,126589.91,A,FR_LD,THS_T,BE
1,60563,59340,62317,67639,66505,68422,76475,78286,89223,92751,...,122302.52,125914.3,126386.94,136321.45,131389,126589.91,A,FR_LD,THS_T,BE2
2,45150,43551,43921,48072,48322,49300,58073,60097,65208,67877,...,102808.48,105332.71,104288.37,109782.57,123540.78,119205.55,A,FR_LD,THS_T,BE21
3,3729,3946,5336,4391,3987,4291,4848,3544,6028,5015,...,7390.23,7671.18,7103.17,6904.52,7848.22,7384.37,A,FR_LD,THS_T,BE23
4,11684,11844,13060,15176,14196,14831,13554,14645,17987,19859,...,12103.81,12910.4,14995.41,19634.36,:,:,A,FR_LD,THS_T,BE25

In [ ]:
df_long = df.melt(
    id_vars=["freq", "tra_meas", "unit", "geo"],
    var_name="year",
    value_name="value"
)

In [ ]:
df_long.head(20)

   freq tra_meas   unit   geo   year   value
0     A    FR_LD  THS_T    BE  1997   60563
1     A    FR_LD  THS_T   BE2  1997   60563
2     A    FR_LD  THS_T  BE21  1997   45150
3     A    FR_LD  THS_T  BE23  1997    3729
4     A    FR_LD  THS_T  BE25  1997   11684
5     A    FR_LD  THS_T    BG  1997       :
6     A    FR_LD  THS_T   BG3  1997       :
7     A    FR_LD  THS_T  BG33  1997       :
8     A    FR_LD  THS_T  BG34  1997       :
9     A    FR_LD  THS_T    CY  1997       :
10    A    FR_LD  THS_T   CY0  1997       :
11    A    FR_LD  THS_T  CY00  1997       :
12    A    FR_LD  THS_T    DE  1997   71512
13    A    FR_LD  THS_T   DE1  1997       :
14    A    FR_LD  THS_T  DE11  1997       :
15    A    FR_LD  THS_T   DE5  1997   11389
16    A    FR_LD  THS_T  DE50  1997   11389
17    A    FR_LD  THS_T   DE6  1997   25014
18    A    FR_LD  THS_T  DE60  1997   25014
19    A    FR_LD  THS_T   DE7  1997       :

In [ ]:
#Volume of containers transported to/from main ports – quarterly data (2025 – 2026)
df2=pd.DataFrame()
df2 = pd.read_table("estat_mar_go_qm_c2026.tsv")
df2.head()

,"freq,par_mar,direct,cargo,loadstat,unit,rep_mar\TIME_PERIOD",2025-Q1,2025-Q2,2025-Q3,2025-Q4
0,"Q,AE,IN,LCNT_20,EMPTY,TEU,BE",197,20,:,:
1,"Q,AE,IN,LCNT_20,EMPTY,TEU,BE_0BE003",197,20,:,:
2,"Q,AE,IN,LCNT_20,EMPTY,TEU,CY",0,0,:,:
3,"Q,AE,IN,LCNT_20,EMPTY,TEU,CY_0CYLMS",0,0,:,:
4,"Q,AE,IN,LCNT_20,EMPTY,TEU,DE",57,175,:,:

In [ ]:
df2 = format_df(df2, ["freq", "par_mar", "direct", "cargo", "loadstat", "unit", "rep_mar"])

df2.head()

,2025-Q1,2025-Q2,2025-Q3,2025-Q4,freq,par_mar,direct,cargo,loadstat,unit,rep_mar
0,197,20,:,:,Q,AE,IN,LCNT_20,EMPTY,TEU,BE
1,197,20,:,:,Q,AE,IN,LCNT_20,EMPTY,TEU,BE_0BE003
2,0,0,:,:,Q,AE,IN,LCNT_20,EMPTY,TEU,CY
3,0,0,:,:,Q,AE,IN,LCNT_20,EMPTY,TEU,CY_0CYLMS
4,57,175,:,:,Q,AE,IN,LCNT_20,EMPTY,TEU,DE

In [ ]:
#Gross weight of goods transported to/from main ports - Germany
df3 = pd.DataFrame()
df3 = pd.read_table("estat_mar_go_am_de.tsv")
df3.head()

,"freq,direct,cargo,natvessr,unit,par_mar,rep_mar\TIME_PERIOD",1997,1998,1999,2000,2001,2002,2003,2004,2005,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,"A,IN,DBK,AE,THS_T,FR,DE",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
1,"A,IN,DBK,AE,THS_T,FR,DE_1",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
2,"A,IN,DBK,AE,THS_T,FR,DE_1DEBKE",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
3,"A,IN,DBK,AE,THS_T,FR_5,DE",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
4,"A,IN,DBK,AE,THS_T,FR_5,DE_1",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:

In [ ]:
df3 = format_df(df3, ["freq", "direct", "cargo", "natvessr", "unit", "par_mar", "rep_mar"])

df3.head(20)

,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,...,2022,2023,2024,freq,direct,cargo,natvessr,unit,par_mar,rep_mar
0,:,:,:,:,:,:,:,:,:,:,...,:,:,:,A,IN,DBK,AE,THS_T,FR,DE
1,:,:,:,:,:,:,:,:,:,:,...,:,:,:,A,IN,DBK,AE,THS_T,FR,DE_1
2,:,:,:,:,:,:,:,:,:,:,...,:,:,:,A,IN,DBK,AE,THS_T,FR,DE_1DEBKE
3,:,:,:,:,:,:,:,:,:,:,...,:,:,:,A,IN,DBK,AE,THS_T,FR_5,DE
4,:,:,:,:,:,:,:,:,:,:,...,:,:,:,A,IN,DBK,AE,THS_T,FR_5,DE_1
5,:,:,:,:,:,:,:,:,:,:,...,:,:,:,A,IN,DBK,AE,THS_T,FR_5,DE_1DEBKE
6,:,:,:,:,:,:,:,:,:,:,...,:,:,:,A,IN,DBK,AE,THS_T,IN,DE
7,:,:,:,:,:,:,:,:,:,:,...,:,:,:,A,IN,DBK,AE,THS_T,IN,DE_1
8,:,:,:,:,:,:,:,:,:,:,...,:,:,:,A,IN,DBK,AE,THS_T,IN,DE_1DEBUZ
9,:,:,:,:,:,:,:,:,:,:,...,:,:,:,A,IN,DBK,AE,THS_T,TOTAL,DE
10,:,:,:,:,:,:,:,:,:,:,...,:,:,:,A,IN,DBK,AE,THS_T,TOTAL,DE_1
11,:,:,:,:,:,:,:,:,:,:,...,:,:,:,A,IN,DBK,AE,THS_T,TOTAL,DE_1DEBKE
12,:,:,:,:,:,:,:,:,:,:,...,:,:,:,A,IN,DBK,AE,THS_T,TOTAL,DE_1DEBUZ
13,:,:,:,:,:,1,:,:,:,:,...,:,:,:,A,IN,DBK,AG,THS_T,AG,DE
14,:,:,:,:,:,1,:,:,:,:,...,:,:,:,A,IN,DBK,AG,THS_T,AG,DE_2
15,:,:,:,:,:,:,:,:,:,:,...,:,:,:,A,IN,DBK,AG,THS_T,AG,DE_2DEGRD
16,:,:,:,:,:,1,:,:,:,:,...,:,:,:,A,IN,DBK,AG,THS_T,AG,DE_2DEKEL
17,:,:,:,:,:,:,:,:,:,:,...,:,:,:,A,IN,DBK,AG,THS_T,AGG_NSP,DE
18,:,:,:,:,:,:,:,:,:,:,...,:,:,:,A,IN,DBK,AG,THS_T,AGG_NSP,DE_1
19,:,:,:,:,:,:,:,:,:,:,...,:,:,:,A,IN,DBK,AG,THS_T,AGG_NSP,DE_1DECUX

In [ ]:
import polars as pl